version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: 192.168.1.3
    volumes:
      - /home/test/mysql1:/var/lib/mysql 
    networks:
      network:
        ipv4_address: 192.168.1.2
  gunicorn:
    image: drowzzzy/appex
    networks:
      network:
        ipv4_address: 192.168.1.3
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1        
