"""Initial migration

Revision ID: 1a4589709f1f
Revises: 
Create Date: 2024-01-15 11:21:22.812187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4589709f1f'
down_revision = None
branch_labels = None
depends_on = None


from app import db
from models import Car, Order
def insert_data():
    # Добавление данных в таблицу Car
    car1 = Car(model='Kia Rio', driver='Корунов Александр Владимирович', number='а712ее99', on_duty=True)
    car2 = Car(model='Lada Vesta', driver='Рунов Дмитрий Борисович', number='а171мр97', on_duty=False)
    car3 = Car(model='Kia Optima', driver='Косачков Кирилл Павлович', number='м196ос50', on_duty=True)

    db.session.add_all([car1, car2, car3])
    db.session.commit()

    # Добавление данных в таблицу Order
    order1 = Order(car_id=1, passenger='Корунов Александр Владимирович', destination='Беговая, 5', sms_code='7124')
    order2 = Order(car_id=3, passenger='Косачков Кирилл Павлович', destination='Аргуновская, 8', sms_code='1981')

    db.session.add_all([order1, order2])
    db.session.commit()

if __name__ == '__main__':
    insert_data()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('driver', sa.String(length=100), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('on_duty', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car')),
    sa.UniqueConstraint('number', name=op.f('uq_car_number'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_user_phone_number'))
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('passenger', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('sms_code', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], name=op.f('fk_order_car_id_car')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    
    )
    insert_data()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('car')
    # ### end Alembic commands ###



